language: julia
julia:
  - 0.4
  - 0.5
  - nightly
notifications:
  email: false
# custom script to grab the unregistered ExpmV and QuantumInfo packages
script:
 - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
 - julia -e 'Pkg.clone("https://github.com/marcusps/ExpmV.jl.git"); Pkg.clone("https://github.com/BBN-Q/SchattenNorms.jl.git"); Pkg.clone("https://bitbucket.org/marcusps/quantuminfo.jl.git", "QuantumInfo")'
 - julia --check-bounds=yes -e 'Pkg.clone(pwd()); Pkg.build("QSimulator"); Pkg.test("QSimulator"; coverage=true)'

# necessary to run on new container-based infrastructure
sudo: false
